export const BRANDS_LIST_FETCH_REQUEST = 'BRANDS_LIST_FETCH_REQUEST';
export const BRANDS_LIST_FETCH_SUCCESS = 'BRANDS_LIST_FETCH_SUCCESS';
export const BRANDS_LIST_FETCH_FAILURE = 'BRANDS_LIST_FETCH_FAILURE';
export const BRANDS_LIST_RESET         = 'BRANDS_LIST_RESET';
export const BRANDS_LIST_ROW_SELECT    = 'BRANDS_LIST_ROW_SELECT';
export const BRANDS_LIST_ROW_UPDATE    = 'BRANDS_LIST_ROW_UPDATE';

export const BRANDS_LIST_MODAL_SHOW    = 'BRANDS_LIST_MODAL_SHOW';
export const BRANDS_LIST_MODAL_CLOSE   = 'BRANDS_LIST_MODAL_CLOSE';

export const BRANDS_LIST_DELETE_REQUEST = 'BRANDS_LIST_DELETE_REQUEST';
export const BRANDS_LIST_DELETE_SUCCESS = 'BRANDS_LIST_DELETE_SUCCESS';
export const BRANDS_LIST_DELETE_FAILURE = 'BRANDS_LIST_DELETE_FAILURE';

export const BRANDS_LIST_SAVE_REQUEST  = 'BRANDS_LIST_SAVE_REQUEST';
export const BRANDS_LIST_SAVE_SUCCESS  = 'BRANDS_LIST_SAVE_SUCCESS';
export const BRANDS_LIST_SAVE_FAILURE  = 'BRANDS_LIST_SAVE_FAILURE';

