export const CAR_LIST_REQUEST = 'CAR_LIST_REQUEST';
export const CAR_LIST_SUCCESS = 'CAR_LIST_SUCCESS';
export const CAR_LIST_FAILURE = 'CAR_LIST_FAILURE';
export const CAR_LIST_RESET   = 'CAR_LIST_RESET';

export const CAR_LIST_FILTERS_RESET  = 'CAR_LIST_FILTERS_RESET';
export const CAR_LIST_ENABLE_ACTIONS = 'CAR_LIST_ENABLE_ACTIONS';

export const CAR_LIST_DELETE_REQUEST = 'CAR_LIST_DELETE_REQUEST';
export const CAR_LIST_DELETE_SUCCESS = 'CAR_LIST_DELETE_SUCCESS';
export const CAR_LIST_DELETE_FAILURE = 'CAR_LIST_DELETE_FAILURE';
export const CAR_LIST_DELETE_SHOW    = 'CAR_LIST_DELETE_SHOW';
export const CAR_LIST_DELETE_CLOSE   = 'CAR_LIST_DELETE_CLOSE';

export const CAR_CHANGE_TRANSITION   = 'CAR_CHANGE_TRANSITION';
export const CAR_CHANGE_CLOSE        = 'CAR_CHANGE_CLOSE';
export const CAR_CHANGE_CHECK_REQUEST = 'CAR_CHANGE_CHECK_REQUEST';
export const CAR_CHANGE_CHECK_ACCEPT  = 'CAR_CHANGE_CHECK_ACCEPT';

export const CAR_CHANGE_SAVE_REQUEST = 'CAR_CHANGE_SAVE_REQUEST';
export const CAR_CHANGE_SAVE_SUCCESS = 'CAR_CHANGE_SAVE_SUCCESS';
export const CAR_CHANGE_SAVE_FAILURE = 'CAR_CHANGE_SAVE_FAILURE';

export const CAR_CACHE_LOAD_REQUEST = 'CAR_CACHE_LOAD_REQUEST';
export const CAR_CACHE_LOAD_SUCCESS = 'CAR_CACHE_LOAD_SUCCESS';
export const CAR_CACHE_LOAD_FAILURE = 'CAR_CACHE_LOAD_FAILURE';

export const CAR_BRAND_LIST_REQUEST = 'CAR_BRAND_LIST_REQUEST';
export const CAR_BRAND_LIST_SUCCESS = 'CAR_BRAND_LIST_SUCCESS';
export const CAR_BRAND_LIST_FAILURE = 'CAR_BRAND_LIST_FAILURE';
export const CAR_BRAND_LIST_RESET   = 'CAR_BRAND_LIST_RESET';
export const CAR_BRAND_ENABLE_ACTIONS = 'CAR_BRAND_ENABLE_ACTIONS';

export const CAR_BRAND_DELETE_SHOW = 'CAR_BRAND_DELETE_SHOW';
export const CAR_BRAND_DELETE_CLOSE = 'CAR_BRAND_DELETE_CLOSE';
export const CAR_BRAND_DELETE_REQUEST = 'CAR_BRAND_DELETE_REQUEST';
export const CAR_BRAND_DELETE_SUCCESS = 'CAR_BRAND_DELETE_SUCCESS';
export const CAR_BRAND_DELETE_FAILURE = 'CAR_BRAND_DELETE_FAILURE';

export const CAR_BRAND_SAVE_REQUEST = 'CAR_BRAND_SAVE_REQUEST';
export const CAR_BRAND_SAVE_SUCCESS = 'CAR_BRAND_SAVE_SUCCESS';
export const CAR_BRAND_SAVE_FAILURE = 'CAR_BRAND_SAVE_FAILURE';

export const CAR_BRAND_CHANGE_ROW = 'CAR_BRAND_CHANGE_ROW';