export const CAR_LIST_REQUEST = 'CAR_LIST_REQUEST';
export const CAR_LIST_SUCCESS = 'CAR_LIST_SUCCESS';
export const CAR_LIST_FAILURE = 'CAR_LIST_FAILURE';
export const CAR_LIST_RESET   = 'CAR_LIST_FAILURE';

export const CAR_LIST_FILTERS_RESET  = 'CAR_LIST_FILTERS_RESET';
export const CAR_LIST_ENABLE_ACTIONS = 'CAR_LIST_ENABLE_ACTIONS';

export const CAR_LIST_DELETE_REQUEST = 'CAR_LIST_DELETE_REQUEST';
export const CAR_LIST_DELETE_SUCCESS = 'CAR_LIST_DELETE_SUCCESS';
export const CAR_LIST_DELETE_FAILURE = 'CAR_LIST_DELETE_FAILURE';
export const CAR_LIST_DELETE_SHOW    = 'CAR_LIST_DELETE_SHOW';
export const CAR_LIST_DELETE_CLOSE   = 'CAR_LIST_DELETE_CLOSE';