export const CARS_LIST_FETCH_REQUEST = 'CARS_LIST_FETCH_REQUEST';
export const CARS_LIST_FETCH_SUCCESS = 'CARS_LIST_FETCH_SUCCESS';
export const CARS_LIST_FETCH_FAILURE = 'CARS_LIST_FETCH_FAILURE';
export const CARS_LIST_RESET_FILTERS = 'CARS_LIST_RESET_FILTERS';
export const CARS_LIST_RESET         = 'CARS_LIST_RESET';
export const CARS_LIST_ROW_SELECT    = 'CARS_LIST_ROW_SELECT';

export const CARS_LIST_MODAL_SHOW    = 'CARS_LIST_MODAL_SHOW';
export const CARS_LIST_MODAL_CLOSE   = 'CARS_LIST_MODAL_CLOSE';

export const CARS_LIST_DELETE_REQUEST = 'CARS_LIST_DELETE_REQUEST';
export const CARS_LIST_DELETE_SUCCESS = 'CARS_LIST_DELETE_SUCCESS';
export const CARS_LIST_DELETE_FAILURE = 'CARS_LIST_DELETE_FAILURE';

export const CARS_FORM_INIT          = 'CARS_FORM_INIT';
export const CARS_FORM_DESTROY       = 'CARS_FORM_DESTROY';
export const CARS_FORM_CHECK_REQUEST = 'CARS_FORM_CHECK_REQUEST';
export const CARS_FORM_CHECK_SUCCESS = 'CARS_FORM_CHECK_SUCCESS';
export const CARS_FORM_CHECK_FAILURE = 'CARS_FORM_CHECK_FAILURE';
export const CARS_FORM_SAVE_REQUEST  = 'CARS_FORM_SAVE_REQUEST';
export const CARS_FORM_SAVE_SUCCESS  = 'CARS_FORM_SAVE_SUCCESS';
export const CARS_FORM_SAVE_FAILURE  = 'CARS_FORM_SAVE_FAILURE';

export const CARS_CACHE_LOAD_REQUEST = 'CARS_CACHE_LOAD_REQUEST';
export const CARS_CACHE_LOAD_SUCCESS = 'CARS_CACHE_LOAD_SUCCESS';
export const CARS_CACHE_LOAD_FAILURE = 'CARS_CACHE_LOAD_FAILURE';