export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE';
export const USER_LIST_RESET   = 'USER_LIST_RESET';

export const USER_ENABLE_ACTIONS = 'USER_ENABLE_ACTIONS';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE';
export const USER_DELETE_SHOW    = 'USER_DELETE_SHOW';
export const USER_DELETE_CLOSE   = 'USER_DELETE_CLOSE';