export const USERS_LIST_FETCH_REQUEST = 'USERS_LIST_FETCH_REQUEST';
export const USERS_LIST_FETCH_SUCCESS = 'USERS_LIST_FETCH_SUCCESS';
export const USERS_LIST_FETCH_FAILURE = 'USERS_LIST_FETCH_FAILURE';
export const USERS_LIST_RESET         = 'USERS_LIST_RESET';

export const USERS_LIST_ROW_SELECT    = 'USERS_LIST_ROW_SELECT';

export const USERS_LIST_MODAL_SHOW    = 'USERS_LIST_MODAL_SHOW';
export const USERS_LIST_MODAL_CLOSE   = 'USERS_LIST_MODAL_CLOSE';

export const USERS_LIST_DELETE_REQUEST = 'USERS_LIST_DELETE_REQUEST';
export const USERS_LIST_DELETE_SUCCESS = 'USERS_LIST_DELETE_SUCCESS';
export const USERS_LIST_DELETE_FAILURE = 'USERS_LIST_DELETE_FAILURE';