export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE';
export const USER_LIST_RESET   = 'USER_LIST_RESET';

export const USER_ENABLE_ACTIONS = 'USER_ENABLE_ACTIONS';