export const LOGGED_USER_REQUEST = 'users/LOGGED_USER_REQUEST';
export const LOGGED_USER_SUCCESS = 'users/LOGGED_USER_SUCCESS';
export const LOGGED_USER_FAILURE = 'users/LOGGED_USER_FAILURE';

export const FETCH_USERS_REQUEST = 'users/FETCH_LIST_REQUEST';
export const FETCH_USERS_SUCCESS = 'users/FETCH_LIST_SUCCESS';
export const FETCH_USERS_FAILURE = 'users/FETCH_LIST_FAILURE';

export const CREATE_USER_REQUEST = 'users/CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'users/CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'users/CREATE_USER_FAILURE';

export const CHANGE_USER_REQUEST = 'users/CHANGE_USER_REQUEST';
export const CHANGE_USER_SUCCESS = 'users/CHANGE_USER_SUCCESS';
export const CHANGE_USER_FAILURE = 'users/CHANGE_USER_FAILURE';